application: codeme-apac
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30s"

libraries:
- name: jinja2
  version: "latest"
- name: lxml
  version: "latest"

handlers:

- url: /$
  static_files: html/index.html
  upload: html/index.html

# index files
- url: /(.+)/
  static_files: html/\1/index.html
  upload: html/(.+)/index.html

- url: /
  static_dir: html
